# Generated by Django 3.0.6 on 2021-12-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(default='uploads/products/ring_tile.jpg', upload_to='uploads/products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(default='uploads/products/ring_tile.jpg', upload_to='uploads/products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image4',
            field=models.ImageField(default='uploads/products/ring_tile.jpg', upload_to='uploads/products/'),
        ),
    ]
